name: WORKFLOW

on:
  push:
    branches:
      - master # Set a branch to deploy when pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: commit linting check
        uses: uptownaravi/verify-commit-message-action@v2
        with:
          regex: '^(?=.{0,72}$)(vim-patch.*|(ci|fix|feat|docs|test|perf|refactor|chore|build)(\([^)]+\))?!?:\s[a-z].*[^.]$)'

      - name: Install
        run: npm install
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: react-app:latest
